/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spvessel_glfwwrapper_GlfwWrapper */

#ifndef _Included_com_spvessel_glfwwrapper_GlfwWrapper
#define _Included_com_spvessel_glfwwrapper_GlfwWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_init
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_terminate
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    swapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_swapInterval
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    swapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_swapBuffers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getClipboardString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getClipboardString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setClipboardString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setClipboardString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    waitEventsTimeout
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_waitEventsTimeout
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    waitEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_waitEvents
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    pollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_pollEvents
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setCursorPosCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWCursorPosCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setCursorPosCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setMouseButtonCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWMouseButtonCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setMouseButtonCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setScrollCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWScrollCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setScrollCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setKeyCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWKeyCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setKeyCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setCharModsCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWCharModsCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setCharModsCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowCloseCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowCloseCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowCloseCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowPosCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowPosCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowPosCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowFocusCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowFocusCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowFocusCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowSizeCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowSizeCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowSizeCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowIconifyCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowIconifyCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowIconifyCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowRefreshCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowRefreshCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowRefreshCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setFramebufferSizeCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWFramebufferSizeCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setFramebufferSizeCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowContentScaleCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWWindowContentScaleCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowContentScaleCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setDropCallback
 * Signature: (JLcom/spvessel/glfwwrapper/GLFWDropCallback;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setDropCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    windowHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_windowHint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    createWindow
 * Signature: (IILjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_createWindow
  (JNIEnv *, jobject, jint, jint, jstring, jlong, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowShouldClose
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowShouldClose
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    windowShouldClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_windowShouldClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    makeContextCurrent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_makeContextCurrent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowPos
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowPos
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getWindowPos
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getWindowPos
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowSize
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getWindowSize
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getWindowSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowSizeLimits
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowSizeLimits
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowAspectRatio
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowAspectRatio
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    showWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_showWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    hideWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_hideWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getWindowContentScale
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getWindowContentScale
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    maximizeWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_maximizeWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    restoreWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_restoreWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    focusWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_focusWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    iconifyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_iconifyWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    destroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_destroyWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowIcon
 * Signature: (JI[Lcom/spvessel/glfwwrapper/GLFWImage;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowIcon
  (JNIEnv *, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getPrimaryMonitor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getPrimaryMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getMonitorWorkarea
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getMonitorWorkarea
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setWindowMonitor
 * Signature: (JJIIIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setWindowMonitor
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getFramebufferSize
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getFramebufferSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getVideoMode
 * Signature: (J)Lcom/spvessel/glfwwrapper/GLFWVidMode;
 */
JNIEXPORT jobject JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getVideoMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getMonitorContentScale
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getMonitorContentScale
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    createStandardCursor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_createStandardCursor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    createCursor
 * Signature: (Lcom/spvessel/glfwwrapper/GLFWImage;II)J
 */
JNIEXPORT jlong JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_createCursor
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    setCursor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_setCursor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_spvessel_glfwwrapper_GlfwWrapper
 * Method:    getCursorPos
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_spvessel_glfwwrapper_GlfwWrapper_getCursorPos
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
