/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper */

#ifndef _Included_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
#define _Included_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    ActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_ActiveTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    AttachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_AttachShader
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BindBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BindFramebuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BindRenderbuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BindRenderbuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    FramebufferRenderbuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_FramebufferRenderbuffer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BindVertexArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BindVertexArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BlendFuncSeparate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BufferDataf
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BufferDataf
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BufferDatai
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BufferDatai
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteFramebuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteFramebuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteRenderbuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteRenderbuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    RenderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_RenderbufferStorage
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    CompileShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_CompileShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    CreateProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_CreateProgram
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    CreateShader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_CreateShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DetachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DetachShader
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DisableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DisableVertexAttribArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    EnableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_EnableVertexAttribArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    FramebufferTexture
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_FramebufferTexture
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GenBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GenBuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GenFramebuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GenFramebuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GenRenderbuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GenRenderbuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GenVertexArray
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GenVertexArray
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteVertexArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteVertexArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GetUniformLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GetUniformLocation
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    LinkProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_LinkProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    ShaderSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_ShaderSource
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    TexStorage2D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_TexStorage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Uniform1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Uniform1f
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Uniform1fv
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Uniform1fv
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Uniform1i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Uniform1i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Uniform2fv
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Uniform2fv
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Uniform3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Uniform3f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Uniform4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Uniform4f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    UniformMatrix4fv
 * Signature: (IIZ[F)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_UniformMatrix4fv
  (JNIEnv *, jobject, jint, jint, jboolean, jfloatArray);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    UseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_UseProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    VertexAttribPointer
 * Signature: (IIIZIJ)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_VertexAttribPointer
  (JNIEnv *, jobject, jint, jint, jint, jboolean, jint, jlong);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Viewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Viewport
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    ClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_ClearColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Finish
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Enable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Enable
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Disable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Disable
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    CullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_CullFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BindTexture
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Hint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Hint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GetIntegerv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GetIntegerv
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    GenTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_GenTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    BlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_BlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    TexImage2DEmpty
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_TexImage2DEmpty
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    TexImage2D
 * Signature: (IIIIIIII[B)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_TexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    TexSubImage2D
 * Signature: (IIIIIIII[B)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_TexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    TexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_TexParameteri
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DrawArrays
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DrawElements
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DrawElements
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DeleteTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DeleteTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    DrawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_DrawBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    Scissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_Scissor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    ClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_ClearStencil
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    StencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_StencilFunc
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    StencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_StencilMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper
 * Method:    StencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_spvessel_spacevil_internal_Wrapper_OpenGLWrapper_StencilOp
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
