package com.spvessel.spacevil.Flags;

public enum EmbeddedImage {
    ADD, ARROW_LEFT, EYE, FILE, FOLDER, FOLDER_PLUS, GEAR, IMPORT, LINES, LOUPE, RECYCLE_BIN, REFRESH, PENCIL, DISKETTE,
    ERASER, HOME, USER, DRIVE, FILTER, ARROW_UP
}